name: 'Trigger: External request to build and publish all images'

on: workflow_dispatch

jobs:

  build_and_publish_all_dev_images:
    uses: itopia-inc/spaces-images/.github/workflows/build_and_publish_all_images.yaml@main
    with:
      environment: "dev"

  build_and_publish_all_prod_images:
    needs: build_and_publish_all_dev_images
    uses: itopia-inc/spaces-images/.github/workflows/build_and_publish_all_images.yaml@main
    with:
      environment: "prod"
