name: 'Trigger: PR with workflow change'

on:
  pull_request:
    branches:
    - main
    paths:
    - '.github/workflows/build_and_publish_all_images.yaml'
    - '.github/workflows/build_and_publish_changed_images.yaml'
    - '.github/workflows/on_pr_with_source_or_workflow_change.yaml'

jobs:

  build_and_publish_all_dev_images:
    uses: itopia-inc/spaces-images/.github/workflows/build_and_publish_all_images.yaml@main
    with:
      environment: "dev"
